#!/bin/bash

#this script compiles each of the five networking files and creates an
#executable compatible with the grading script.
gcc -o keygen keygen.c -g   
gcc -o otp_enc otp_enc.c -g
gcc -o otp_enc_d otp_enc_d.c -g 
gcc -o otp_dec otp_dec.c -g
gcc -o otp_dec_d otp_dec_d.c -g
